# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fede/PCSC_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fede/PCSC_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fede/PCSC_project/CMakeFiles /home/fede/PCSC_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fede/PCSC_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PCSC_fourier

# Build rule for target.
PCSC_fourier: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PCSC_fourier
.PHONY : PCSC_fourier

# fast build rule for target.
PCSC_fourier/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/build
.PHONY : PCSC_fourier/fast

src/BMPInput.o: src/BMPInput.cpp.o
.PHONY : src/BMPInput.o

# target to build an object file
src/BMPInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/BMPInput.cpp.o
.PHONY : src/BMPInput.cpp.o

src/BMPInput.i: src/BMPInput.cpp.i
.PHONY : src/BMPInput.i

# target to preprocess a source file
src/BMPInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/BMPInput.cpp.i
.PHONY : src/BMPInput.cpp.i

src/BMPInput.s: src/BMPInput.cpp.s
.PHONY : src/BMPInput.s

# target to generate assembly for a file
src/BMPInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/BMPInput.cpp.s
.PHONY : src/BMPInput.cpp.s

src/CSVOutput.o: src/CSVOutput.cpp.o
.PHONY : src/CSVOutput.o

# target to build an object file
src/CSVOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/CSVOutput.cpp.o
.PHONY : src/CSVOutput.cpp.o

src/CSVOutput.i: src/CSVOutput.cpp.i
.PHONY : src/CSVOutput.i

# target to preprocess a source file
src/CSVOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/CSVOutput.cpp.i
.PHONY : src/CSVOutput.cpp.i

src/CSVOutput.s: src/CSVOutput.cpp.s
.PHONY : src/CSVOutput.s

# target to generate assembly for a file
src/CSVOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/CSVOutput.cpp.s
.PHONY : src/CSVOutput.cpp.s

src/Fourier.o: src/Fourier.cpp.o
.PHONY : src/Fourier.o

# target to build an object file
src/Fourier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Fourier.cpp.o
.PHONY : src/Fourier.cpp.o

src/Fourier.i: src/Fourier.cpp.i
.PHONY : src/Fourier.i

# target to preprocess a source file
src/Fourier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Fourier.cpp.i
.PHONY : src/Fourier.cpp.i

src/Fourier.s: src/Fourier.cpp.s
.PHONY : src/Fourier.s

# target to generate assembly for a file
src/Fourier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Fourier.cpp.s
.PHONY : src/Fourier.cpp.s

src/Histogram.o: src/Histogram.cpp.o
.PHONY : src/Histogram.o

# target to build an object file
src/Histogram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Histogram.cpp.o
.PHONY : src/Histogram.cpp.o

src/Histogram.i: src/Histogram.cpp.i
.PHONY : src/Histogram.i

# target to preprocess a source file
src/Histogram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Histogram.cpp.i
.PHONY : src/Histogram.cpp.i

src/Histogram.s: src/Histogram.cpp.s
.PHONY : src/Histogram.s

# target to generate assembly for a file
src/Histogram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Histogram.cpp.s
.PHONY : src/Histogram.cpp.s

src/Input.o: src/Input.cpp.o
.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i
.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s
.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/Output.o: src/Output.cpp.o
.PHONY : src/Output.o

# target to build an object file
src/Output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Output.cpp.o
.PHONY : src/Output.cpp.o

src/Output.i: src/Output.cpp.i
.PHONY : src/Output.i

# target to preprocess a source file
src/Output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Output.cpp.i
.PHONY : src/Output.cpp.i

src/Output.s: src/Output.cpp.s
.PHONY : src/Output.s

# target to generate assembly for a file
src/Output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Output.cpp.s
.PHONY : src/Output.cpp.s

src/PNGOutput.o: src/PNGOutput.cpp.o
.PHONY : src/PNGOutput.o

# target to build an object file
src/PNGOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/PNGOutput.cpp.o
.PHONY : src/PNGOutput.cpp.o

src/PNGOutput.i: src/PNGOutput.cpp.i
.PHONY : src/PNGOutput.i

# target to preprocess a source file
src/PNGOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/PNGOutput.cpp.i
.PHONY : src/PNGOutput.cpp.i

src/PNGOutput.s: src/PNGOutput.cpp.s
.PHONY : src/PNGOutput.s

# target to generate assembly for a file
src/PNGOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/PNGOutput.cpp.s
.PHONY : src/PNGOutput.cpp.s

src/Visualizer.o: src/Visualizer.cpp.o
.PHONY : src/Visualizer.o

# target to build an object file
src/Visualizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Visualizer.cpp.o
.PHONY : src/Visualizer.cpp.o

src/Visualizer.i: src/Visualizer.cpp.i
.PHONY : src/Visualizer.i

# target to preprocess a source file
src/Visualizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Visualizer.cpp.i
.PHONY : src/Visualizer.cpp.i

src/Visualizer.s: src/Visualizer.cpp.s
.PHONY : src/Visualizer.s

# target to generate assembly for a file
src/Visualizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/Visualizer.cpp.s
.PHONY : src/Visualizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCSC_fourier.dir/build.make CMakeFiles/PCSC_fourier.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PCSC_fourier"
	@echo "... src/BMPInput.o"
	@echo "... src/BMPInput.i"
	@echo "... src/BMPInput.s"
	@echo "... src/CSVOutput.o"
	@echo "... src/CSVOutput.i"
	@echo "... src/CSVOutput.s"
	@echo "... src/Fourier.o"
	@echo "... src/Fourier.i"
	@echo "... src/Fourier.s"
	@echo "... src/Histogram.o"
	@echo "... src/Histogram.i"
	@echo "... src/Histogram.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/Output.o"
	@echo "... src/Output.i"
	@echo "... src/Output.s"
	@echo "... src/PNGOutput.o"
	@echo "... src/PNGOutput.i"
	@echo "... src/PNGOutput.s"
	@echo "... src/Visualizer.o"
	@echo "... src/Visualizer.i"
	@echo "... src/Visualizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

